### ISSUE TITLE
"another process is accessing the bl-net"

### ISSUE THREAD

**Issue by nils50122** [berwinter/uvr1611#21]
hello,

i upgrade today from my uvr1611 + bl-net to uvr16x2 with an C.M.I.

Now my DataLoggerPro shows the error "another process is accessing the bl-net".

I test the connection with same url and same port and i became data.
I test the connection with this browser url "http://xxx:2522/LOG/infoh.log" and download the newest data in a .txt file.

my config.ini is here:
`[mysql]
server = localhost
user = xxx
password = xxx
database = xxx

[uvr1611]
logger = "cmi"
blnet_login = false
address = xxx
port = 40000
reset = true
http_port = 2522

[app]
name = "xxx"
debug = false
email = xxx
chartcache = 600
latestcache = 60
reduction = 2`

**Comment by berwinter** [comment]
Could you please try to set the port to 80? The CMI doesn't have an dedicated port for datalogging (WinSOL). All data is transferred through port 80.

**Comment by nils50122** [comment]
Now i become an next error "Device with code 0x87 and CAN id 1 not supported" after this, the same another process is accessing the bl-net.

**Comment by berwinter** [comment]
Currently the dataset format for a device with the code 0x87 is unknown. Is this your upgraded CMI and uvr16x2 with 64 datasets? Maybe TA gave it a new device code in order to differentiate between the old and new implementation.

**Comment by nils50122** [comment]
Yes, its the UVR16x2 with FW 1.22 and i think with 64 datasheets.
I would be very happy when you integrate the new datastream to your logger.

**Comment by nils50122** [comment]
Any news? For me the implemation of an UVR16x2 into DataLoggerPro is important.

**Comment by NoelHendrikx** [comment]
I also upgraded my UVR and receive the same error message: "Device with code 0x87 and CAN id 1 not supported"

**Comment by NoelHendrikx** [comment]
emabled debug flag, output of dump:

#0 /share/MD0_DATA/Web/uvr/lib/backend/cmi-parser.inc.php(82): CmiDataset->getFrameId()↵#1 /share/MD0_DATA/Web/uvr/lib/backend/cmi-parser.inc.php(164): CmiDataset->getFormat()↵#2 /share/MD0_DATA/Web/uvr/lib/backend/cmi-connection.inc.php(103): CmiParser->addDataset('C\x00\x01\x87\x00\x00\x00\x00\x01\x01\x04\x00\x00\x00\x00...')↵#3 /share/MD0_DATA/Web/uvr/lib/backend/cmi-connection.inc.php(44): CmiConnection->getCount()↵#4 /share/MD0_DATA/Web/uvr/latest.php(25): CmiConnection->getLatest()↵#5 {main}
