### ISSUE TITLE
only 16 analog/digital values for 64 available from UVR16x2

### ISSUE THREAD

**Issue by nils50122** [berwinter/uvr1611#22]
hello,

is there a solution to upgrade the 16 analog/digital values in the dataloggerpro to 64 analog and digital values?

with the last update the UVR16x2 sends a datalogging string with 64 available values for each analog and digital.

big thanks!

**Comment by berwinter** [comment]
Unfortunately this is currently not supported. Implementing up to 64 channels would need significant modifications in the datalogger code and the database schema.

**Comment by bobosch** [comment]
Perhaps store them as 4 frames in the t_data table?

**Comment by nils50122** [comment]
Any news? For me the implemation of an UVR16x2 into DataLoggerPro is important.

**Comment by berwinter** [comment]
Duplicate of #21

**Comment by berwinter** [comment]
I made an new branch for the 64-channel implementation:
[uvr16x2-64-channels](/berwinter/uvr1611/tree/uvr16x2-64-channels)

As I do not have an UVR16x2 and CMI I would need the /LOG/infoh.log file from an updated CMI/UVR16x2. I can have a look at the setup and define the mapping for multiple frames in t_data.

However best would be to rework the whole database into a more flexible structure, which would give better performance in this situation.

**Comment by bobosch** [comment]
I think the current database format is quite a good compromise between flexible and storage efficient (less overhead).

**Comment by NoelHendrikx** [comment]
attached my ingoh.log

[infoh.zip](https://github.com/berwinter/uvr1611/files/871001/infoh.zip)

**Comment by NoelHendrikx** [comment]
I deployed the new branch and launched latest.php.

{"stacktrace":"#0 \/share\/MD0_DATA\/Web\/uvr\/lib\/backend\/cmi-parser.inc.php(105): CmiDataset->getFrameId()\n#1 \/share\/MD0_DATA\/Web\/uvr\/lib\/backend\/cmi-parser.inc.php(189): CmiDataset->getFormat()\n#2 \/share\/MD0_DATA\/Web\/uvr\/lib\/backend\/cmi-connection.inc.php(103): CmiParser->addDataset('C\\x00\\x01\\x87\\x00\\x00\\x00\\x00\\x01\\x01\\x04\\x00\\x00\\x00\\x00...')\n#3 \/share\/MD0_DATA\/Web\/uvr\/lib\/backend\/cmi-connection.inc.php(44): CmiConnection->getCount()\n#4 \/share\/MD0_DATA\/Web\/uvr\/latest.php(25): CmiConnection->getLatest()\n#5 {main}","message":"Device with code 0x87 and CAN id 1 not supported."}

**Comment by berwinter** [comment]
I updated the mapping. "Device with code 0x87 not supported" messages should be gone now.
Unfortunately it seems that the implementation is not as simple as I expected. It seems that TA made the format more flexible and direct mapping to 4 conventional frames is not sufficient. There are up to 64 analog values which can be either temperature, power or energy. Depending on the unit the right field in the Datalogger frame need to assigned (temperature to analog1-16, power to power1,2, energy to energy1,2). Once the available fields for one type is filled, the next frame has to be used. This is currently not implemented, all analog values are written into the analog1-16 fields regardless of their unit.

**Comment by NoelHendrikx** [comment]
Nice, I get the info now again (in a different format as well, but I will manage to read the structure for now)
![image](https://cloud.githubusercontent.com/assets/8036578/24631790/f0a7f20c-18c1-11e7-880b-6c48ef63d439.png)

**Comment by NoelHendrikx** [comment]
{"frame1":{"date":"2017-04-03 23:02:40","energy1":"NULL","energy2":"NULL","analog1":45.8,"analog2":45.1,"analog3":39.4,"analog4":34.2,"analog5":18.3,"analog6":19.3,"analog7":"NULL","analog8":10.4,"analog9":19.4,"analog10":19.2,"analog11":"NULL","analog12":21.7,"analog13":"NULL","analog14":"NULL","analog15":"NULL","analog16":"NULL","digital1":"NULL","digital2":0,"digital3":"NULL","digital4":"NULL","digital5":0,"digital6":0,"digital7":0,"digital8":0,"digital9":"NULL","digital10":"NULL","digital11":"NULL","digital12":"NULL","digital13":"NULL","digital14":"NULL","digital15":"NULL","digital16":"NULL","speed1":"NULL","speed2":"NULL","speed3":"NULL","speed4":"NULL","power1":"NULL","power2":"NULL","kWh1":"NULL","MWh1":"NULL","kWh2":"NULL","MWh2":"NULL","current_energy1":null,"current_energy2":null},"frame2":{"date":"2017-04-03 23:02:40","energy1":"NULL","energy2":"NULL","analog1":"NULL","analog2":"NULL","analog3":0,"analog4":"NULL","analog5":"NULL","analog6":"NULL","analog7":"NULL","analog8":"NULL","analog9":"NULL","analog10":"NULL","analog11":"NULL","analog12":"NULL","analog13":"NULL","analog14":"NULL","analog15":"NULL","analog16":"NULL","digital1":"NULL","digital2":"NULL","digital3":"NULL","digital4":"NULL","digital5":"NULL","digital6":"NULL","digital7":"NULL","digital8":"NULL","digital9":"NULL","digital10":"NULL","digital11":"NULL","digital12":"NULL","digital13":"NULL","digital14":"NULL","digital15":"NULL","digital16":"NULL","speed1":"NULL","speed2":"NULL","speed3":"NULL","speed4":"NULL","power1":"NULL","power2":"NULL","kWh1":"NULL","MWh1":"NULL","kWh2":"NULL","MWh2":"NULL","current_energy1":null,"current_energy2":null},"time":"05:03:04","info":{"cached":false}}

**Comment by nils50122** [comment]
Is there now a solution?

**Comment by NoelHendrikx** [comment]
Yes for me it works :)

![image](https://cloud.githubusercontent.com/assets/8036578/24898154/240ce50a-1e9c-11e7-8d91-9252535a9a81.png)

**Comment by nils50122** [comment]
Can you explain what i have to do?

**Comment by NoelHendrikx** [comment]
https://github.com/berwinter/uvr1611/tree/uvr16x2-64-channels
Download that branch and copy it over the current version except your own ini file

**Comment by nils50122** [comment]
I delete complete filesystem, download the latest version 2.12 and install again.

I become now the message "another process is accessing the bl-net".

**Comment by berwinter** [comment]
The implementation is not complete yet. However you should be able to get at least the temperature values into the database. If you give me more feedback which values are not read correctly, I can improve the mapping and parser scripts.

As Noel mentioned you have to download the special 64-channel branch:
[uvr16x2-64-channels](https://github.com/berwinter/uvr1611/archive/uvr16x2-64-channels.zip)

Regarding the error message: it should go aways automatically after 10minutes. You can also manually delete the file `/tmp/uvr1611-logger.pid`. This should remove the message.

**Comment by Gamerios** [comment]
any news ?

**Also we have at the Analog 5   a Strömugswächter but it is shown as °C  hw we can manage to show it as EIN AUS   because its at sensor not as digital output its digital input    .** 


With digital poutputs it work EIN / AUS show in extras stats at same chart site but with the  Strömungswächter not


**Also how can use more units / formats in one chart ? because at Solar CHarts the Durchfluss Solar is shown as °C to but thats not reight how we can fix that ?**


I read values from UVR16x2 with RP3 and Can Bus Shield .  and upload values to mysql Datalogger from this github.

**Comment by nils50122** [comment]
> https://github.com/berwinter/uvr1611/tree/uvr16x2-64-channels
> Download that branch and copy it over the current version except your own ini file

can you please reupload the 64 channel version?

**Comment by bobosch** [comment]
I've added the correct conversion for different units 1a35ec8ccdb8d9b9a2b68c631ee32e22e18d2cff
